### ISSUE TITLE
Add settings page to launcher

### ISSUE THREAD

**Issue by rinrincodes** [hawka97/mcforge-launcher#8]
We still need to think of what to put in it as it is just an empty form. Maybe @hawka97 has some better ideas but I really can't think of anything to put in it right now.

**Comment by hawka97** [comment]
`Reset and restart` and `Delete and close` have been added. Do you have any other ideas? Otherwise, this will be closed.

**Comment by rinrincodes** [comment]
Nothing else is going to be added to the settings page. Closing this now.
