### ISSUE TITLE
Switch between macOS UI buttons and Windows UI buttons in title bar of launcher

### ISSUE THREAD

**Issue by rinrincodes** [hawka97/mcforge-launcher#9]
To make the launcher buttons look a bit nicer and more professional, I was thinking about making some glyphs that'll make the launcher UI buttons in the title bar a bit nicer and to change them appropriately on which OS that your using. For Linux builds in the near future, they'll use the same Windows styled ones.

**Comment by hawka97** [comment]
Sure. When you make them, attach them to this GH Issue

**Comment by rinrincodes** [comment]
Already pretty much covered now with the new macOS UI.
